alter table RETENTION_COPILOT.RAW.CUSTOMERS
  modify column LAST_NAME set masking policy RETENTION_COPILOT.GOVERNANCE.MASK_NAME;

alter table RETENTION_COPILOT.RAW.CUSTOMERS
  modify column EMAIL set masking policy RETENTION_COPILOT.GOVERNANCE.MASK_EMAIL;

alter table RETENTION_COPILOT.RAW.CUSTOMERS
  modify column PHONE set masking policy RETENTION_COPILOT.GOVERNANCE.MASK_PHONE;

alter dynamic table RETENTION_COPILOT.ANALYTICS.CUSTOMER_PROFILE
  modify column LAST_NAME set masking policy RETENTION_COPILOT.GOVERNANCE.MASK_NAME;

alter dynamic table RETENTION_COPILOT.ANALYTICS.CUSTOMER_PROFILE
  modify column EMAIL set masking policy RETENTION_COPILOT.GOVERNANCE.MASK_EMAIL;

alter dynamic table RETENTION_COPILOT.ANALYTICS.CUSTOMER_PROFILE
  modify column PHONE set masking policy RETENTION_COPILOT.GOVERNANCE.MASK_PHONE;
