create or replace view RETENTION_COPILOT.APP.ACTION_DECISION_LOG as
select
  d.DECISION_ID,
  d.ACTION_ID,
  a.CUSTOMER_ID,
  c.FIRST_NAME,
  c.CITY,
  a.ACTION_TYPE,
  d.DECISION,
  d.NOTE,
  d.PREVIOUS_STATUS,
  d.DECIDED_BY,
  d.DECIDED_AT
from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS d
join RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS a on a.ACTION_ID = d.ACTION_ID
join RETENTION_COPILOT.RAW.CUSTOMERS c on c.CUSTOMER_ID = a.CUSTOMER_ID
order by d.DECIDED_AT desc;

create or replace view RETENTION_COPILOT.APP.GUARDRAIL_LOG as
select
  USAGE_TIME,
  AGENTIC_SOURCE,
  USER_NAME
from SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_GUARDRAILS_USAGE_HISTORY
where GUARDRAILS_SIGNAL = true
order by USAGE_TIME desc
limit 100;
