create or replace task RETENTION_COPILOT.ANALYTICS.ENRICH_NEW_CALLS_TASK
  warehouse = RETENTION_COPILOT_WH
  schedule = '1 minute'
  when SYSTEM$STREAM_HAS_DATA('RETENTION_COPILOT.RAW.CALL_TRANSCRIPT_STREAM')
  as
  call RETENTION_COPILOT.ANALYTICS.ENRICH_NEW_CALLS();

alter task RETENTION_COPILOT.ANALYTICS.ENRICH_NEW_CALLS_TASK resume;
