insert into RETENTION_COPILOT.RAW.CALL_TRANSCRIPTS
  (TRANSCRIPT_ID, CUSTOMER_ID, TICKET_ID, CALL_AT, DURATION_SECONDS, AGENT_ID, TRANSCRIPT_TEXT)
select
  'CALL009999',
  CUSTOMER_ID,
  TICKET_ID,
  CALL_AT,
  DURATION_SECONDS,
  AGENT_ID,
  TRANSCRIPT_TEXT
from RETENTION_COPILOT.RAW.CALL_TRANSCRIPTS
where TRANSCRIPT_ID = 'CALL000001';

execute task RETENTION_COPILOT.ANALYTICS.ENRICH_NEW_CALLS_TASK;

call system$wait(90);

select TRANSCRIPT_ID, SENTIMENT_SCORE, MAIN_TOPIC, WANTS_TO_CANCEL
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS
where TRANSCRIPT_ID = 'CALL009999';

alter task RETENTION_COPILOT.ANALYTICS.ENRICH_NEW_CALLS_TASK suspend;

create or replace temporary table TEMP_CLEANUP_STREAM as
  select TRANSCRIPT_ID from RETENTION_COPILOT.RAW.CALL_TRANSCRIPT_STREAM;

delete from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS where TRANSCRIPT_ID = 'CALL009999';

delete from RETENTION_COPILOT.RAW.CALL_TRANSCRIPTS where TRANSCRIPT_ID = 'CALL009999';

alter task RETENTION_COPILOT.ANALYTICS.ENRICH_NEW_CALLS_TASK resume;

select count(*) as CALL_INSIGHTS_COUNT from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS;

select count(*) as CALL_TRANSCRIPTS_COUNT from RETENTION_COPILOT.RAW.CALL_TRANSCRIPTS;

show tasks like 'ENRICH_NEW_CALLS_TASK' in schema RETENTION_COPILOT.ANALYTICS;
