use role ACCOUNTADMIN;
use warehouse RETENTION_COPILOT_WH;

show agents in schema RETENTION_COPILOT.APP;

describe agent RETENTION_COPILOT.APP.RETENTION_AGENT;

show grants to role RETENTION_COPILOT_READER;

select count(*) as ACTION_DECISIONS_ROW_COUNT
from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS;

select STATUS, count(*) as ACTION_COUNT
from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS
group by STATUS
order by STATUS;
