use role ACCOUNTADMIN;
use warehouse RETENTION_COPILOT_WH;

select STATUS, count(*) as ACTION_COUNT
from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS
group by STATUS
order by STATUS;

select count(*) as ACTION_DECISIONS_ROW_COUNT
from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS;

select ACTION_ID, STATUS as ORIGINAL_STATUS, PRIORITY_RANK
from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS
order by PRIORITY_RANK desc
limit 1;

call RETENTION_COPILOT.APP.RECORD_ACTION_DECISION(
    (select ACTION_ID from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS order by PRIORITY_RANK desc limit 1),
    'Dismissed',
    'automated test'
);

select ACTION_ID, STATUS as STATUS_AFTER_DISMISS
from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS
where ACTION_ID = (
    select ACTION_ID from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS order by PRIORITY_RANK desc limit 1
);

select DECISION_ID, ACTION_ID, DECISION, NOTE, PREVIOUS_STATUS, DECIDED_BY, DECIDED_AT
from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS
order by DECISION_ID desc
limit 1;

call RETENTION_COPILOT.APP.RECORD_ACTION_DECISION('ACT999999', 'Dismissed', 'test');

call RETENTION_COPILOT.APP.RECORD_ACTION_DECISION('ACT999999', 'Deleted', 'test');

update RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS
set STATUS = (
    select PREVIOUS_STATUS
    from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS
    where NOTE = 'automated test'
    order by DECISION_ID desc
    limit 1
)
where ACTION_ID = (
    select ACTION_ID from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS order by PRIORITY_RANK desc limit 1
);

delete from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS
where NOTE = 'automated test';

select STATUS, count(*) as ACTION_COUNT
from RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS
group by STATUS
order by STATUS;

select count(*) as LEFTOVER_TEST_ROWS
from RETENTION_COPILOT.ANALYTICS.ACTION_DECISIONS
where NOTE = 'automated test';
