create or replace view RETENTION_COPILOT.APP.CUSTOMER_OVERVIEW as
select
    cp.CUSTOMER_ID,
    cp.FIRST_NAME,
    cp.CITY,
    cp.STATE,
    cp.SEGMENT,
    cp.TENURE_MONTHS,
    cp.ACTIVE_POLICIES,
    cp.TOTAL_MONTHLY_PREMIUM,
    cp.PRODUCTS_HELD,
    cp.LATE_PAYMENTS,
    cp.FAILED_PAYMENTS,
    cp.LATE_OR_FAILED_RATE,
    cp.CLAIMS_COUNT,
    cp.OPEN_CLAIMS,
    cp.REJECTED_CLAIMS,
    cp.TICKETS_COUNT,
    cp.OPEN_TICKETS,
    cp.ESCALATED_TICKETS,
    cp.AVERAGE_SATISFACTION,
    cp.CALLS_COUNT,
    cp.AVERAGE_SENTIMENT,
    cp.NEGATIVE_CALLS,
    cp.RIVAL_MENTIONS,
    cp.CANCEL_INTENT_CALLS,
    cs.CHURN_PROBABILITY,
    cs.RISK_TIER,
    cs.TOP_DRIVER_1,
    cs.TOP_DRIVER_2,
    cs.TOP_DRIVER_3,
    ra.ACTION_ID,
    ra.ACTION_TYPE,
    ra.CHANNEL as ACTION_CHANNEL,
    ra.REASON as ACTION_REASON,
    ra.CONFIDENCE as ACTION_CONFIDENCE,
    ra.STATUS as ACTION_STATUS,
    ra.PRIORITY_RANK,
    ra.REVENUE_AT_RISK,
    ra.DRAFT_MESSAGE
from RETENTION_COPILOT.ANALYTICS.CUSTOMER_PROFILE cp
inner join RETENTION_COPILOT.ANALYTICS.CHURN_SCORES cs
    on cp.CUSTOMER_ID = cs.CUSTOMER_ID
left join RETENTION_COPILOT.ANALYTICS.RECOMMENDED_ACTIONS ra
    on cp.CUSTOMER_ID = ra.CUSTOMER_ID
where cp.IS_ACTIVE_AT_CUTOFF = true
