create or replace view RETENTION_COPILOT.APP.CALL_OVERVIEW as
select
    ci.TRANSCRIPT_ID,
    ci.CUSTOMER_ID,
    cp.FIRST_NAME,
    cp.CITY,
    ci.CALL_AT,
    ci.SENTIMENT_SCORE,
    ci.MAIN_TOPIC,
    ci.COMPETITOR_MENTIONED,
    ci.COMPLAINT_REASON,
    ci.WANTS_TO_CANCEL,
    ct.TRANSCRIPT_TEXT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS ci
inner join RETENTION_COPILOT.RAW.CALL_TRANSCRIPTS ct
    on ci.TRANSCRIPT_ID = ct.TRANSCRIPT_ID
inner join RETENTION_COPILOT.ANALYTICS.CUSTOMER_PROFILE cp
    on ci.CUSTOMER_ID = cp.CUSTOMER_ID
