create or replace cortex search service RETENTION_COPILOT.APP.CALL_SEARCH
  on TRANSCRIPT_TEXT
  attributes TRANSCRIPT_ID, CUSTOMER_ID, FIRST_NAME, CITY, CALL_AT, SENTIMENT_SCORE, MAIN_TOPIC, COMPETITOR_MENTIONED, WANTS_TO_CANCEL
  warehouse = RETENTION_COPILOT_WH
  target_lag = '1 day'
as
select
    ci.TRANSCRIPT_ID,
    ci.CUSTOMER_ID,
    c.FIRST_NAME,
    c.CITY,
    ci.CALL_AT,
    ci.SENTIMENT_SCORE,
    ci.MAIN_TOPIC,
    ci.COMPETITOR_MENTIONED,
    ci.WANTS_TO_CANCEL,
    ct.TRANSCRIPT_TEXT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS ci
inner join RETENTION_COPILOT.RAW.CALL_TRANSCRIPTS ct
    on ci.TRANSCRIPT_ID = ct.TRANSCRIPT_ID
inner join RETENTION_COPILOT.RAW.CUSTOMERS c
    on ci.CUSTOMER_ID = c.CUSTOMER_ID
