grant select on view RETENTION_COPILOT.APP.CUSTOMER_OVERVIEW to role RETENTION_COPILOT_READER;
grant select on view RETENTION_COPILOT.APP.CALL_OVERVIEW to role RETENTION_COPILOT_READER;
grant select on semantic view RETENTION_COPILOT.APP.CHURN_SEMANTIC_VIEW to role RETENTION_COPILOT_READER;
grant usage on cortex search service RETENTION_COPILOT.APP.CALL_SEARCH to role RETENTION_COPILOT_READER;
grant database role SNOWFLAKE.CORTEX_ANALYST_USER to role RETENTION_COPILOT_READER
