use role ACCOUNTADMIN;
use warehouse RETENTION_COPILOT_WH;

call RETENTION_COPILOT.GENERATOR.WRITE_TRANSCRIPT_BATCH(61, 300);
call RETENTION_COPILOT.GENERATOR.WRITE_TRANSCRIPT_BATCH(301, 550);
call RETENTION_COPILOT.GENERATOR.WRITE_TRANSCRIPT_BATCH(551, 800);
call RETENTION_COPILOT.GENERATOR.WRITE_TRANSCRIPT_BATCH(801, 1000);
