use role ACCOUNTADMIN;
use warehouse RETENTION_COPILOT_WH;

call RETENTION_COPILOT.ANALYTICS.ENRICH_CALLS(1, 250);
call RETENTION_COPILOT.ANALYTICS.ENRICH_CALLS(251, 500);
call RETENTION_COPILOT.ANALYTICS.ENRICH_CALLS(501, 750);
call RETENTION_COPILOT.ANALYTICS.ENRICH_CALLS(751, 1000);
