use role ACCOUNTADMIN;
use warehouse RETENTION_COPILOT_WH;

select count(*) as ROW_COUNT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS;

select
    count_if(SENTIMENT_SCORE is null) as NULL_SENTIMENT_SCORE,
    count_if(MAIN_TOPIC is null) as NULL_MAIN_TOPIC,
    count_if(COMPETITOR_MENTIONED is null) as NULL_COMPETITOR_MENTIONED,
    count_if(COMPLAINT_REASON is null) as NULL_COMPLAINT_REASON,
    count_if(WANTS_TO_CANCEL is null) as NULL_WANTS_TO_CANCEL
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS;

select
    avg(SENTIMENT_SCORE) as AVG_SENTIMENT,
    min(SENTIMENT_SCORE) as MIN_SENTIMENT,
    max(SENTIMENT_SCORE) as MAX_SENTIMENT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS;

select
    MAIN_TOPIC,
    count(*) as TOPIC_COUNT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS
group by MAIN_TOPIC
order by TOPIC_COUNT desc;

select
    COMPETITOR_MENTIONED,
    count(*) as COMPETITOR_COUNT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS
group by COMPETITOR_MENTIONED
order by COMPETITOR_COUNT desc;

select
    WANTS_TO_CANCEL,
    count(*) as WANTS_TO_CANCEL_COUNT
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS
group by WANTS_TO_CANCEL;

select
    case
        when c.MOOD < 0.3 then 'below 0.3'
        when c.MOOD <= 0.7 then '0.3 to 0.7'
        else 'above 0.7'
    end as MOOD_CATEGORY,
    count(*) as CALLS,
    avg(i.SENTIMENT_SCORE) as AVG_SENTIMENT_SCORE
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS i
join RETENTION_COPILOT.GENERATOR.CUSTOMER_MOOD c
  on i.CUSTOMER_ID = c.CUSTOMER_ID
group by MOOD_CATEGORY
order by AVG_SENTIMENT_SCORE;

select *
from RETENTION_COPILOT.ANALYTICS.CALL_INSIGHTS
limit 5;
